# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 17:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(b'draft', b'Draft'), (b'approved', b'Approved')], default=b'draft', max_length=255)),
                ('publish_timestamp', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(max_length=255)),
                ('link', models.URLField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['publish_timestamp'],
                'verbose_name_plural': 'Facebook Statuses',
            },
        ),
    ]
